const Products = [
  {
    id: "product-01",
    name: "The Boolean Egyptian",
    cover:
      "https://res.cloudinary.com/yheenca/image/upload/v1669896798/artsy/product/4764a7daa106cda4888b058654d2bf6f_b5w6au.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "Egypt",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$135.90",
    featured: true,
  },
  {
    id: "product-02",
    name: "The First Men",
    cover:
      "https://res.cloudinary.com/yheenca/image/upload/v1669896809/artsy/product/fb3d9960288826716a27d9959abf72a8_twt7aq.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "Egypt",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$138.90",
    featured: true,
  },
  {
    id: "product-03",
    name: "Le' Sparta",
    cover:
      "https://res.cloudinary.com/yheenca/image/upload/v1669896818/artsy/product/f3fde95f8e3bc2f6fee4e448074c8c47_za95et.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "Italy",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$158.70",
    featured: true,
  },
  {
    id: "product-04",
    name: "Philomena' 22",
    cover: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "Australia",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$38.90",
    featured: false,
  },
  {
    id: "product-05",
    name: "Blanc",
    cover: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "Australia",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$25.10",
    featured: false,
  },
  {
    id: "product-06",
    name: "Ellipsia",
    cover: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "United States",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$38.90",
    featured: false,
  },
  {
    id: "product-07",
    name: "The Law Makers",
    cover: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "Australia",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$18.90",
    featured: false,
  },
  {
    id: "product-08",
    name: "Veil",
    cover: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "Germany",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$38.90",
    featured: false,
  },
  {
    id: "product-09",
    name: "Alternating",
    cover: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "Japan",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$38.90",
    featured: false,
  },
  {
    id: "product-10",
    name: "Rosemary' 22",
    cover: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "England",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$38.90",
    featured: false,
  },
  {
    id: "product-11",
    name: "Beverly",
    cover: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor pur",
    country: "South Korea",
    creator: "Ali Dawa",
    curators_id: [
      "curator-01",
      "curator-02",
      "curator-03",
      "curator-04",
      "curator-05",
    ],
    status: ["Auction", "Sale"],
    price: "$38.90",
    featured: false,
  },
];

export default Products;
